### ISSUE TITLE
Increase the Hertz rate

### ISSUE THREAD

**Issue by pramathk** [ChristopheJacquet/PiFmRds#155] opened 2020-08-28 03:46 UTC
Please could you increase the hertz rate? the songs playing from the PiFmRds is like 1990 song. If you could some how increase the rate it would be better

**Comment by ChristopheJacquet** [comment] 2021-01-04 21:32
I'm not sure what the problem is. Is the sound playing too slow? Then this would be the problem investigated in #159.

**Comment by ChristopheJacquet** [comment] 2024-03-02 15:18
Duplicate of #159

**Comment by ChristopheJacquet** [comment] 2024-03-02 15:19
Duplicate of #159

**Closed by ChristopheJacquet** 2024-03-02 15:18 UTC
