### ISSUE TITLE
sudo ./pi_fm_rds not found

### ISSUE THREAD

**Issue by DylanHP** [ChristopheJacquet/PiFmRds#118] opened 2018-12-23 12:00 UTC
help me the command sudo ./pi_fm_rds dont work i have made all what is listed including the make  but the program doesnt work

**Comment by StoneSet** [comment] 2018-12-30 20:04
Do /home/pi//home/pi/PiFmRds/src/pi_fm_rds

**Comment by DylanHP** [comment] 2018-12-30 20:50
Thanks StoneSet I have another answer why I can only transmit for a few seconds like 30 sec my music over a determined frequency?? After this 30 seconds the radio transmission restart

**Comment by StoneSet** [comment] 2018-12-30 20:58
Which command do you use?

**Comment by saintofinternet** [comment] 2019-01-15 05:47
> 
> 
> help me the command sudo ./pi_fm_rds dont work i have made all what is listed including the make but the program doesnt work

i am still getting the same error and it's not getting solved as per the instructions on this page. can someone help?

**Comment by sarimbinwaseem** [comment] 2019-01-26 12:04
Some problem ... nothing works

**Comment by ChristopheJacquet** [comment] 2019-07-31 22:12
This is most likely a duplicate of #126 which is fixed now (see #125). I also updated the README to explain that the pi_fm_rds executable is missing iff make fails.

Marking this issue as fixed (because #126 was fixed). Please open a new issue with the error message if make is failing for any other reason.

**Closed by ChristopheJacquet** 2019-07-31 22:12 UTC
