### ISSUE TITLE
./pi_fm_rds: command not found issue

### ISSUE THREAD

**Issue by CodeDev1809** [ChristopheJacquet/PiFmRds#131] opened 2019-07-25 23:35 UTC
Hello Github,
As you can probably tell but the title I have gotten the ./pi_fm_rds: command not found error. I have followed the instructions exactly (I'm pretty sure). Does anyone have any ideas as to how I can solve this error?
Thank you!

**Comment by ChristopheJacquet** [comment] 2019-07-31 21:58
This is most likely a duplicate of #126 which is fixed now (see #125). I also updated the README to explain that the `pi_fm_rds` executable is missing iff `make` fails.

Marking this issue as fixed (because #126 was fixed). Please open a new issue with the error message if `make` is failing for any other reason.

**Closed by ChristopheJacquet** 2019-07-31 21:58 UTC
