### ISSUE TITLE
Speed of song is slowed down after an attempt to extend the range by connecting a wire much more than recommended 20 cm to the GPIO 3 pin

### ISSUE THREAD

**Issue by Faiz7412** [ChristopheJacquet/PiFmRds#120] opened 2018-12-26 13:26 UTC
This is embarrassing, the audio output is slowed down. I got excited and wanted to experiment with a longer GPIO wire length, and drive around in my neighborhood while listening to my favorite songs.  I think the safety limit of the GPIO pin was interfered with and since then there is a high-pitched sound along with the songs in about 0.5x speed. I've also tried with GPIO32 pin using the `pi_fm_adv` code, so I guess I messed up the clock. Any fix?

**Comment by ChristopheJacquet** [comment] 2019-08-01 10:29
Duplicate of #75 
This is most probably not directly related to the wire you added.
May you try adding `gpu_freq=250` to `/boot/config.txt` and comment on #75?

**Comment by ChristopheJacquet** [comment] 2019-08-01 10:29
Duplicate of #75

**Closed by ChristopheJacquet** 2019-08-01 10:29 UTC
