### ISSUE TITLE
pi_fm_rds with mplayer

### ISSUE THREAD

**Issue by hello-folks** [ChristopheJacquet/PiFmRds#100] opened 2017-12-12 13:48 UTC
Hello

I use pi_fm_rds with raspberry pi2.

So,I'd like to use pi_fm_rds with mplayer.

I make this command

mplayer -ao pcm:file=/dev/stdout -really-quiet 01.mp3 | sudo ./pi_fm_rds -freq 80.0 -audio -

It is success to hear from my FM radio.
But sound is slow.

What wrong ?

My *.mp3 is 44.1khz/16bit(normal)

Best Regard

**Comment by Niall7459** [comment] 2018-01-10 16:08
Im getting this problem as well. Never used to get it until I had to reformat my raspberry pi with the new versionn :(

**Comment by ChristopheJacquet** [comment] 2019-08-01 10:26
Most probably duplicate of #75. May you try adding `gpu_freq=250` to `/boot/config.txt` and comment on #75?

**Comment by ChristopheJacquet** [comment] 2019-08-01 10:27
Duplicate of #75

**Closed** 2019-08-01 10:27 UTC
