### ISSUE TITLE
Issues caused by speakers

### ISSUE THREAD

**Issue by hxxr** [ChristopheJacquet/PiFmRds#67] opened 2016-10-01 13:28 UTC
If I play something on the Raspberry Pi 2's default sound card to the speakers, for example, using `sox`, then use PiFmRds, the signal will be noticeably slowed down (for me, it sounds one whole step lower), and after this, if I try playing something through speakers again, I just hear this garbled mess.

Oh yeah, restarting does fix this, but nothing else will.

**Comment by ChristopheJacquet** [comment] 2019-08-01 15:57
Duplicate of #7

**Closed** 2019-08-01 15:57 UTC
Labels: duplicate
